Models/Coments.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Diars_Espinoza_Nolasco_Jeffrey_T1_Examen.Models
{
    public class Coments
    {
        public int Id { get; set; }
        public String Opinion { get; set; }
        public DateTime Fecha_Comentario { get; set; }
        public int IdPost { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Diars_Espinoza_Nolasco_Jeffrey_T1_Examen.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Mapeo/ComentsMapeo.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Diars_Espinoza_Nolasco_Jeffrey_T1_Examen.Models.Mapeo
{
    public class ComentsMapeo : IEntityTypeConfiguration<Coments>
    {

        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Coments> builder)
        {
            builder.ToTable("Coments");
            builder.HasKey(o => o.Id);
        }
    }
}

Models/Mapeo/Post_Mapeo.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Diars_Espinoza_Nolasco_Jeffrey_T1_Examen.Models.Mapeo
{
    public class Post_Mapeo : IEntityTypeConfiguration<Postcs>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Postcs> builder)
        {
            builder.ToTable("Postcs");
            builder.HasKey(o => o.Id);

            builder.HasMany(o => o.Coments).WithOne().HasForeignKey(o => o.IdPost);
        }
    }
}

Models/Postcs.cs
using Diars_Espinoza_Nolasco_Jeffrey_T1_Examen.Models.Mapeo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Diars_Espinoza_Nolasco_Jeffrey_T1_Examen.Models
{
    public class Postcs
    {
        public int Id { get; set; }
        public String Nombre_Post { get; set; }
        public String Autor_Post { get; set; }
        public String Contenido_Post { get; set; }
        public DateTime Fecha_Post { get; set; }
        public List<Coments> Coments { get; set; }


    }
}

Models/T1_Diars_Context.cs
using Diars_Espinoza_Nolasco_Jeffrey_T1_Examen.Models.Mapeo;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Diars_Espinoza_Nolasco_Jeffrey_T1_Examen.Models
{
    public class T1_Diars_Context : DbContext
    {
        public DbSet<Postcs> Posts { get; set; }
        public DbSet<Coments> Coments { get; set; }
        public T1_Diars_Context(DbContextOptions<T1_Diars_Context> options)
            : base(options) { }
            protected override void OnModelCreating(ModelBuilder modelBouilder)
        {
            modelBouilder.ApplyConfiguration(new Post_Mapeo());
            modelBouilder.ApplyConfiguration(new ComentsMapeo());
        }

    }
}

Controllers/HomeController.cs
using Diars_Espinoza_Nolasco_Jeffrey_T1_Examen.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Diars_Espinoza_Nolasco_Jeffrey_T1_Examen.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PostController.cs
using Diars_Espinoza_Nolasco_Jeffrey_T1_Examen.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Diars_Espinoza_Nolasco_Jeffrey_T1_Examen.Controllers
{
    public class PostController : Controller
    {
        private readonly T1_Diars_Context context;
        // GET: PostController
        public PostController(T1_Diars_Context context)
        {
            this.context = context;
        }
        [HttpGet]
        public ActionResult Index()
        {
            var post = context.Posts.OrderByDescending(o => o.Fecha_Post).ToList();
            return View(post);
        }

        [HttpPost]
        public ActionResult Registrar(Postcs post)
        {
            post.Fecha_Post = DateTime.Now;
            context.Posts.Add(post);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Registrar()
        {
            return View("Registrar", new Postcs());
        }
        [HttpGet]
        public ActionResult Detalle(int id)
        {
            var post = context.Posts.Where(o => o.Id == id).FirstOrDefault();
            ViewBag.Coments = context.Coments.Where(o => o.IdPost == id).OrderByDescending(o => o.Fecha_Comentario).ToList();
            return View(post);
        }
        [HttpPost]
        public ActionResult RegistrarComentario(Coments coments)
        {
            coments.Fecha_Comentario = DateTime.Now;
            context.Add(coments);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult RegistrarComentario(int idP)
        {
            ViewBag.Id = idP;
            Console.WriteLine(ViewBag.Id);
            return View("RegistrarComentario",new Coments());
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Post/Detalle.cshtml
@{ 
    var post = (Postcs)Model;
    var comentarios = (List<Coments>)ViewBag.Coments;
}

<div>
    <h3>@post.Nombre_Post</h3>
    <div>
        <p><strong>Autor: </strong> @post.Autor_Post</p>
        <p><strong>Fecha de Creacion: </strong>@post.Fecha_Post</p>
        <div>
            <p><strong>Contenido</strong> </p>
        </div>
        <p>@post.Contenido_Post</p>
    </div>
</div>

<div>
    <h2>___[COMENTARIOS]___</h2>

    <a href="/Post/RegistrarComentario?idP=@post.Id">Nuevo comentario</a>

    <div>
        @foreach (var item in comentarios)
        {
            <p>@item.Opinion</p>
            <p><strong>fecha creacion:</strong>@item.Fecha_Comentario</p>
        }
    </div>
</div>

Views/Post/Index.cshtml
@{ 
    var post = (List<Postcs>)Model;
}
<h1>Post de T1 Diars</h1>
<a href="/post/registrar">Crear Blog</a>
</br>
<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>autor</th>
            <th>Fceha de Publicacion</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in post)
        {
        <tr>
            <td>@item.Nombre_Post</td>
            <td>@item.Autor_Post</td>
            <td>@item.Fecha_Post</td>
            <td><a href="/Post/Detalle?id=@item.Id">Detalle</a></td>
        </tr>
        }
    </tbody>

</table>

Views/Post/Registrar.cshtml
@{
    var post = (Postcs)Model;
}

<h1>Registrar Post</h1>

<form action="/Post/Registrar" method="post">
    Nombre <input class="form-control" name="Nombre_Post" />
    Autor <input class="form-control" name="Autor_Post" />
    Contenido <textarea class="form-control" name="Contenido_Post" rows="3"></textarea>
    <div></div>
    <button class="btn btn-primary">Guardar</button>
</form>

Views/Post/RegistrarComentario.cshtml
<div>
    <form action="/Post/RegistrarComentario" method="post">

        <input type="hidden" name="IdPost" value="@ViewBag.Id"/>

        <div>
            <textarea class="form-control" name="Opinion" placeholder="Ingresar nuevo comentario"></textarea>
        </div>

        <button class="btn btn-primary">Comentario</button>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Diars_Espinoza_Nolasco_Jeffrey_T1_Examen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Diars_Espinoza_Nolasco_Jeffrey_T1_Examen</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Post</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Diars_Espinoza_Nolasco_Jeffrey_T1_Examen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>